### ISSUE TITLE
perf/js-libp2p: `Expected to receive 104857600 bytes, but received 48693248`

### ISSUE THREAD

**Issue by mxinden** [libp2p/test-plans#291]
Tracking `js-libp2p` perf failure here:

```
= Benchmark Single Connection throughput – Download 100 MiB

[ ... ]

== Version js-libp2p/v0.46
=== Starting server js-libp2p/v0.46


=== Starting client js-libp2p/v0.46/tcp
Error: Expected to receive 104857600 bytes, but received 48693248
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54159) - No such process
Error: Expected to receive 104857600 bytes, but received 45744128
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54174) - No such process
Error: Expected to receive 104857600 bytes, but received 44040192
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54191) - No such process
Error: Expected to receive 104857600 bytes, but received 45023232
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54262) - No such process
Error: Expected to receive 104857600 bytes, but received 44498944
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54278) - No such process
Error: Expected to receive 104857600 bytes, but received 45809664
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54293) - No such process
Error: Expected to receive 104857600 bytes, but received 46858240
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54309) - No such process
Error: Expected to receive 104857600 bytes, but received 47251456
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54380) - No such process
Error: Expected to receive 104857600 bytes, but received 45154304
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54396) - No such process
Error: Expected to receive 104857600 bytes, but received 44630016
    at DefaultPerfService.measurePerformance (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/index.js:132:23)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async main (file:///home/ec2-user/impl/js-libp2p/v0.46/js-libp2p-protocol-perf/node_modules/@libp2p/perf/dist/src/main.js:81:26)
./impl/js-libp2p/v0.46/perf: line 6: kill: (54411) - No such process
Command failed: ssh -o StrictHostKeyChecking=no ec2-user@1.2.3.4 'for i in {1..10}; do ./impl/js-libp2p/v0.46/perf --server-address 1.2.3.4:4001 --transport tcp --upload-bytes 0 --download-bytes 104857600; done'
Error: Process completed with exit code 1.
```

https://github.com/libp2p/test-plans/actions/runs/6048547493/job/16414112311

**Comment by mxinden** [comment]
The above error appears consistently across pull requests, when run manually and on `master`.

@maschad do you have an idea what is happening here?

I will revert https://github.com/libp2p/test-plans/pull/244 **for now** to unblock pull requests.

**Comment by maschad** [comment]
I am investigating this, it may be related to https://github.com/libp2p/js-libp2p/issues/2020 but not sure yet.
